name: Generate Snake

on:
  schedule:
    - cron: "*/1 * * * *"  # This cron expression schedules the workflow to run every minute
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: Platane/snk/svg-only@v3
        id: snake-svg
        with:
          github_user_name: Ayush-kathayat
          outputs: |
            dist/github-contribution-grid-snake.svg?palette=github-light
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=#3c7dd9
            dist/github-contribution-grid-snake-default.svg?color_snake=#3c7dd9&color_dots=#ebedf0,#9be9a8,#40c463,#30a14e,#216e39

      - run: git status

      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
